on:
  push:
    branches: main

jobs:
  planner:
    name: Determine which jobs to run
    runs-on: ubuntu-latest
    # To keep it simple name the step and output the same as job
    outputs:
      npm: ${{ steps.npm.outputs.enabled }}
      php: ${{ steps.php.outputs.enabled }}
    steps:
      # Checkout if necessary to determine whether 'foo' needs to run
      - uses: actions/checkout@v4
      - name: Test if npm publish job should run
        if:  ${{ hashFiles('package-lock.json') != '' || hashFiles('yarn.lock') != '' }}
        id: npm
        run: echo "enabled=true" >> $GITHUB_OUTPUT
      - name: Test if php publish job should run
        if:  ${{ hashFiles('composer.lock') != '' }}
        id: php
        run: echo "enabled=true" >> $GITHUB_OUTPUT
  publish-npm:
    runs-on: ubuntu-latest
    needs: planner
    # Skip this job when condition not met
    if: needs.planner.outputs.npm == 'true' 
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}